spring:  
  application:
    name: customer-service
  cloud:
    consul:
      host: 192.168.99.100
      port: 8500
      
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG 
    
---
spring:
  profiles: zone1
  cloud:
    consul:
      discovery:
        instanceZone: zone1

---
spring:
  profiles: zone2
  cloud:
    consul:
      discovery:
        instanceZone: zone2